### ISSUE TITLE
Locomotion with new controller

### ISSUE THREAD

**Issue by Mvivant** [Unity-Technologies/EditorXR#454] opened 2017-12-18 14:48 UTC
Hi, 

I have an issue, I want to create a new free locomotion tools with the 3dRudder foot-controller, so I created a new device input, but [here](https://github.com/Unity-Technologies/EditorVR/blob/development/Scripts/Modules/DeviceInputModule.cs#L62) you block all other devices ```("For now let's filter out any other devices other than VR controller devices; Eventually, we may support mouse / keyboard etc")```, it is possible to remove this condition ?

Thanks

**Comment by Mvivant** [comment] 2018-08-07 13:05
Hello,

Someone can help me or give me answer ? 
Please :)

**Comment by amirebrahimi** [comment] 2018-09-06 04:00
Is it not possible for you to inherit from VRInputDevice?

**Comment by Mvivant** [comment] 2018-09-06 07:26
No, because I want my controller to be a normal input device and not just a VR input device.

**Comment by mtschoen-unity** [comment] 2018-09-21 20:40
Hey there,

Unfortunately, this situation will not work with the way that we assign tools to controllers without a fair amount of re-work. I haven't tested your specific use-case, but in earlier work where we tried to support mouse input, we found that simply adding a non-VR device to an action map cause the mapping of device-to-toolstack to fail and effectively breaks that tool (it is never added to the ToolData and can never be active). It would be a non-trivial refactor to support this use case. We are no longer supporting the input prototype, but aren't yet ready to transition EXR to the new input system. As such, we don't want to allocate any more resources to improving the input system in EXR until this transition happens. At that point, we will definitely ensure support for non-VR input devices like keyboard/mouse/3dRudder.

In the meantime, are you able to support your use case in your fork of EXR? I see there is also a PR related to this issue (#464). Does that solve the issue currently, or is it just something you need to attempt your solution? Since we aren't planning to support this yet, and I don't want to introduce any regressions, I am going to close that PR.

**Closed by mtschoen-unity** 2018-09-21 20:40 UTC
